HW9.
ShuEugene/HW9 pull request #1
Opened 2022-09-30 13:58 UTC by ShuEugene

2022-09-30 15:41 UTC, OlgaLugacheva requested changes

2022-09-30 15:41 UTC, OlgaLugacheva commented on src/HW9/Book.java
> +    Autor autor;
private final

2022-09-30 15:41 UTC, OlgaLugacheva commented on src/HW9/Autor.java
> +package HW9;
название пакета должно быть с маленькой буквы

2022-10-01 05:32 UTC, ShuEugene commented on src/HW9/Book.java
> +    Autor autor;
Поясни, пожалуйста, о чём мне должно сказать это замечание?..

2022-10-01 05:51 UTC, ShuEugene commented on src/HW9/Autor.java
> +package HW9;
Пока ещё не встречал такого правила. Существует такая договорённсть среди разработчиков или это закреплённый где-то стандарт?

2022-10-01 08:10 UTC, merged